# Floodgate prepends a prefix to bedrock usernames to avoid conflicts
# However, certain conflicts can cause issues with some plugins so this prefix is configurable using the property below
# It is recommended to use a prefix that does not contain alphanumerical to avoid the possibility of duplicate usernames.
username-prefix: "*"

# Should spaces be replaced with '_' in bedrock usernames?
replace-spaces: true

hostname-regex: '^user.*'

disconnect:
  # The disconnect message Geyser users should get when connecting
  # to the server with an invalid key
  invalid-name: Unregisted username!
  # The disconnect message Geyser users should get when connecting
  # to the server with the correct key but not with the correct data format
  invalid-address: Your address is not allowed
